version: '3.1'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
  server:
    image: openjdk:21-jdk-slim
    ports:
      - "8080:8080"
    build:
      context: /server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database